version: 2

sources:
  - name: olist_raw
    database: olist_ecommerce
    tables:
      - name: customers
      - name: order_items
      - name: order_payments
      - name: order_reviews
      - name: products
      - name: sellers
      - name: orders